export const Config = {
	//EXPERIMENTS
	EXPERIMENTS: ["data/solar_system.json", "data/threebodyproblem.json"],
	SELECT: 1,

	//COLORS
	BACKGROUND_COLOR: "#000000",
	SHADOW_BLUR: 0.5,

	//ANIMATION
	ITERATIONS: 3,
	TRAIL_LENGTH: 150,
	TRAIL_SIZE: 1.5,
	
	//PLACE CALCULATION
	MAX_ITERATIONS: 1000,
	REVERSAL_TRAIL: 100,
	
	//CANVAS
	WIDTH: window.innerWidth,
	HEIGHT: window.innerHeight,
	SCROLL: 1.1,
	INITIAL_SCROLL: 0.01,
	
	//PHYSICS
	GRAVITATIONAL_CONSTANT: 0.00667,
	FORCE_AMPLITUDE: 50,

	//DWARF
	DWARF_MASS: 0.7,
	DWARF_RADIUS: 0.7
};
